export const AdminPageRoutes = {
   
    ADMIN_DASHBOARD: {
        LABEL: "Dashboard",
        MODULE_NAME: "",        
        SUB_MODULE_NAME: "Dashboard",
        PAGE_NAME: "Dashboard",
        FULL_PATH: "/adminDashboard",        
    },
    ADMIN_MANAGE_USER: {
        LABEL: "Manage Users",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "manageUsers",
        PAGE_NAME: "manageUsers",
        FULL_PATH: "/userManagement/manageUsers",        
    },
    // 
    ADMIN_ADD_USER: {
        LABEL: "Add User",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "manageUsers",
        PAGE_NAME: "manageUsers",
        FULL_PATH: "/userManagement/manageUsers/addUser",        
    },
    ADMIN_EDIT_USER: {
        LABEL: "Edit User",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "manageUsers",
        PAGE_NAME: "editUser",
        FULL_PATH: "/userManagement/manageUsers/editUser/:userId",        
    },
    ADMIN_CONFIGURE_PROFILE_DEFINITION: {
        LABEL: "Configure Profile Definition",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "configureProfileDefinition",
        PAGE_NAME: "configureProfileDefinition",
        FULL_PATH: "/userManagement/configureProfileDefinition",        
    },
    ADMIN_MANAGE_GROUP: {
        LABEL: "Manage Groups",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "manageGroup",
        PAGE_NAME: "manageGroup",
        FULL_PATH: "/userManagement/manageGroup",        
    },
    ADMIN_ADD_USER_GROUP: {
        LABEL: "Manage Groups",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "manageGroup",
        PAGE_NAME: "addUserGroup",
        FULL_PATH: "/userManagement/manageGroup/addUserGroup",        
    },
    ADMIN_PENDING_APPROVALS: {
        LABEL: "Pending Approvals",
        MODULE_NAME: "userManagement",
        SUB_MODULE_NAME: "pendingApprovals",
        PAGE_NAME: "pendingApprovals",
        FULL_PATH: "/userManagement/pendingApprovals",        
    },

    ADMIN_CONTENT_MANAGE_COURSES: {
        LABEL: "Manage Courses",
        MODULE_NAME: "contentManagement",
        SUB_MODULE_NAME: "contentManageCourses",
        PAGE_NAME: "contentManageCourses",
        FULL_PATH: "/contentManagement/contentManageCourses",        
    },
    ADMIN_CONTENT_ADD_COURSE: {
        LABEL: "Add Course",
        MODULE_NAME: "contentManagement",        
        SUB_MODULE_NAME: "contentManageCourses",
        PAGE_NAME: "contentAddCourse",
        FULL_PATH: "/contentManagement/contentManageCourses/contentAddCourse",        
    },
    ADMIN_CONTENT_EDIT_COURSE: {
        LABEL: "Edit Course",
        MODULE_NAME: "contentManagement",        
        SUB_MODULE_NAME: "contentManageCourses",
        PAGE_NAME: "contentEditCourse",
        FULL_PATH: "/contentManagement/contentManageCourses/contentEditCourse/:courseId",        
    },
    ADMIN_CONTENT_MANAGE_ASSET_LIBRARY: {
        LABEL: "Manage Asset Library",
        MODULE_NAME: "manageAssetLibrary",
        SUB_MODULE_NAME: "manageAssetLibrary",
        PAGE_NAME: "manageAssetLibrary",
        FULL_PATH: "/contentManagement/manageAssetLibrary",        
    },
    ADMIN_CONTENT_ADD_ASSET: {
        LABEL: "Add Asset",
        MODULE_NAME: "contentManagement",        
        SUB_MODULE_NAME: "manageAssetLibrary",
        PAGE_NAME: "contentAddAsset",
        FULL_PATH: "/contentManagement/manageAssetLibrary/contentAddAsset/:assetFolderId",        
    },
    ADMIN_CONTENT_EDIT_ASSET: {
        LABEL: "Edit Asset",
        MODULE_NAME: "contentManagement",        
        SUB_MODULE_NAME: "manageAssetLibrary",
        PAGE_NAME: "contentEditAsset",
        FULL_PATH: "/contentManagement/manageAssetLibrary/contentEditAsset/:assetFolderId/:assetId",        
    },
    ADMIN_CONTENT_MANAGE_CURRICULUM_PLANS: {
        LABEL: "Manage Curriculum Plans",
        MODULE_NAME: "manageCurriculumPlans",
        SUB_MODULE_NAME: "manageCurriculumPlans",
        PAGE_NAME: "manageCurriculumPlans",
        FULL_PATH: "/contentManagement/manageCurriculumPlans",        
    },
    ADMIN_CONTENT_MANAGE_CERTIFICATE: {
        LABEL: "Manage Certificates",
        MODULE_NAME: "manageCertificates",
        SUB_MODULE_NAME: "manageCertificates",
        PAGE_NAME: "manageCertificates",
        FULL_PATH: "/contentManagement/manageCertificates",        
    },    
    ADMIN_MANAGE_LEARNING_PATH:{
        LABEL: "Manage Learning Paths",
        MODULE_NAME: "contentManagement",
        SUB_MODULE_NAME: "manageLearningPath",
        PAGE_NAME: "manageLearningPath",
        FULL_PATH: "/contentManagement/manageLearningPath",
    },
    ADMIN_CONTENT_ADD_LEARNING_PATH: {
        LABEL: "Add New Learning Path",
        MODULE_NAME: "contentManagement",        
        SUB_MODULE_NAME: "manageLearningPath",
        PAGE_NAME: "contentAddLearningPath",
        FULL_PATH: "/contentManagement/manageLearningPath/contentAddLearningPath",        
    },
    ADMIN_CONTENT_MANAGE_CERTIFICATE_MAPPING: {
        LABEL: "Manage Certificate Mapping",
        MODULE_NAME: "manageCertificateMapping",
        SUB_MODULE_NAME: "manageCertificateMapping",
        PAGE_NAME: "manageCertificateMapping",
        FULL_PATH: "/contentManagement/manageCertificateMapping",        
    },
    ADMIN_ASSIGNMENT_ONE_TIME_ASSIGNMENT: {
        LABEL: "One Time Assignment",
        MODULE_NAME: "assignment",
        SUB_MODULE_NAME: "oneTimeAssignment",
        PAGE_NAME: "oneTimeAssignment",
        FULL_PATH: "/assignment/oneTimeAssignment",        
    },
    ADMIN_ASSIGNMENT_DEFAULT_ASSIGNMENT_DATES: {
        LABEL: "Default Assignment Dates",
        MODULE_NAME: "assignment",
        SUB_MODULE_NAME: "defaultAssignmentDates",
        PAGE_NAME: "defaultAssignmentDates",
        FULL_PATH: "/assignment/defaultAssignmentDates",        
    },
    ADMIN_ASSET_PREVIEW:{
          LABEL: "PREVIEW OF ASSETS FILE",
        MODULE_NAME: "preview",
        SUB_MODULE_NAME: "preview",
        PAGE_NAME: "PreviewFile",
        FULL_PATH: "/preview", 
    },
    ADMIN_LEADER_BOARD:{
        LABEL: "Leaderboard",
        MODULE_NAME: "",        
        SUB_MODULE_NAME: "leaderBoard",
        PAGE_NAME: "adminLeaderBoard",
        FULL_PATH: "/adminLeaderBoard",   
    },

    /* Reports */
    ADMIN_LEARNER_PROGRESS_REPORT:{
        LABEL: "Learner Progress Report",
        MODULE_NAME: "reports",        
        SUB_MODULE_NAME: "learnerProgressReport",
        PAGE_NAME: "learnerProgressReport",
        FULL_PATH: "/reports/learnerProgressReport",   
    },
}