
export enum ACTION_BUTTON_ENUM {
  ACTIVATE = "ACTIVATE",
  DEACTIVATE = "DEACTIVATE",
  DELETE = "DELETE",
  APPROVE = "APPROVE",
  REJECT = "REJECT"
}

export enum COMMON_TABLE_TYPE {
  MANAGE_USER = "MANAGE_USER",
  PENDING_APPROVALS = "PENDING_APPROVALS",
  MANAGE_GROUP = "MANAGE_GROUP",
  MANAGE_COURSES = "MANAGE_COURSES",
  MANAGE_ASSET_LIBRARY = "MANAGE_ASSET_LIBRARY",
  MANAGE_ONE_TIME_ASSIGNMENT_ACTIVITY = "MANAGE_ONE_TIME_ASSIGNMENT_ACTIVITY",
  MANAGE_ONE_TIME_ASSIGNMENT_USER = "MANAGE_ONE_TIME_ASSIGNMENT_USER",
  MANAGE_ONE_TIME_ASSIGNMENT_USER_BUSINESS_RULE = "MANAGE_ONE_TIME_ASSIGNMENT_USER_BUSINESS_RULE",
  MANAGE_ONE_TIME_ASSIGNMENT_USER_SELECTED = "MANAGE_ONE_TIME_ASSIGNMENT_USER_SELECTED",
  MANAGE_ONE_TIME_ASSIGNMENT_PREVIEW_CONTENT_SELECTED_ACTIVITY = 'MANAGE_ONE_TIME_ASSIGNMENT_PREVIEW_CONTENT_SELECTED_ACTIVITY',
  MANAGE_ONE_TIME_ASSIGNMENT_PREVIEW_CONTENT_SELECTED_USER = 'MANAGE_ONE_TIME_ASSIGNMENT_PREVIEW_CONTENT_SELECTED_USER',
  MANAGE_TREE_COURSES_FILES='MANAGE_TREE_COURSES_FILES',
  MANAGE_ADMIN_LEADERBOARD_USERS='MANAGE_ADMIN_LEADERBOARD_USERS',
  MANAGE_ADMIN_LEARNING_PATH='MANAGE_ADMIN_LEARNING_PATH',
  REPORT_LEARNER_ACTIVITY_PROGRESS='REPORT_LEARNER_ACTIVITY_PROGRESS',
  REPORT_LEARNER_PROGRESS='REPORT_LEARNER_PROGRESS'
}

export enum COMMON_FOLDER_TREEVIEW_TYPE {
  ADD_COURSE_FOLDER_TREE = "ADD_COURSE_FOLDER_TREE",
}

export enum FIELDS_ENUM {
  FIRST_NAME = "FirstName",
  LAST_NAME = "LastName",
  EMAIL_ID = "EmailID",
  LOGIN_ID = "LoginId",
  USER_PASSWORD = "UserPassword",
  USER_CONFIRM_PASSWORD = "confirmPassword", //
  IS_ACTIVE = "IsActive",
  DEFAULT_LANGUAGE_ID = "DefaultLanguageId",
  MANAGER_EMAIL_ID = "ManagerEmailId",
}

export enum ACTIVITY_CONTENT_TYPE_ENUM {
  None = 0,
  Scorm12 = 1, // "Scorm 1.2"
  Scorm2004 = 2, // "Scorm 2004"
  AICC = 3,
  NonCompliant = 4, // "Non Compliant"
  Curriculum = 5,
  Asset = 6,
  Certification = 7,
  Policy = 8,
  Questionnaire = 9,
  Course = 10,
  Assessment = 11,
  Classroom_Training = 12,
  Virtual_Training = 13,
}

export const ACTIVITY_TYPES={
  ASSET:'Asset',
  SCROM12:'Scorm12',
  CIRRICULUM:'Cirriculum'
}